### GET /actuator/health
GET http://localhost:8080/actuator/health

### GET /api/v1/items
GET http://localhost:8080/api/v1/items?page=0&size=20

### POST /api/v1/items
POST http://localhost:8080/api/v1/items
Content-Type: application/json

{
  "name": "B-상의-111",
  "price": 50000,
  "brandId": 2,
  "categoryId": 1
}

> {%
  // 응답에서 필요한 값 추출
  client.global.set("itemId", response.body.id)
%}

### GET /api/v1/items/{itemId}
GET http://localhost:8080/api/v1/items/{{itemId}}

### PUT /api/v1/items/{itemId}
PUT http://localhost:8080/api/v1/items/{{itemId}}
Content-Type: application/json

{
  "name": "C-상의-1112",
  "price": 60000,
  "brandId": 3,
  "categoryId": 1
}

### PATCH /api/v1/items/{itemId}
PATCH http://localhost:8080/api/v1/items/{{itemId}}
Content-Type: application/json

{
  "name": "C-상의-1114444",
  "price": 70001
}

### DELETE /api/v1/items/{itemId}
DELETE http://localhost:8080/api/v1/items/{{itemId}}

### GET /api/v1/brands
GET http://localhost:8080/api/v1/brands?page=0&size=20

### POST /api/v1/brands
POST http://localhost:8080/api/v1/brands
Content-Type: application/json

{
  "name": "Nike"
}

> {%
  // 응답에서 필요한 값 추출
  client.global.set("brandId", response.body.id)
%}

### GET /api/v1/brands/{brandId}
GET http://localhost:8080/api/v1/brands/{{brandId}}

### PUT /api/v1/brands/{brandId}
PUT http://localhost:8080/api/v1/brands/{{brandId}}
Content-Type: application/json

{
  "name": "Adidas"
}

### PATCH /api/v1/brands/{brandId}
PATCH http://localhost:8080/api/v1/brands/{{brandId}}
Content-Type: application/json

{
  "name": "Puma"
}

### DELETE /api/v1/brands/{brandId}
DELETE http://localhost:8080/api/v1/brands/{{brandId}}

### GET /api/v1/categories
GET http://localhost:8080/api/v1/categories

> {%
  // 응답에서 필요한 값 추출
  client.global.set("categoryId", response.body[0].id)
%}

### GET /api/v1/categories/{category-id}
GET http://localhost:8080/api/v1/categories/{{categoryId}}

> {%
  // 응답에서 필요한 값 추출
  client.global.set("categoryId", response.body.id)
  client.global.set("categoryName", response.body.name)
 %}

### GET /api/v1/items/statistics/min-brand-price-group-by-category
GET http://localhost:8080/api/v1/items/statistics/min-brand-price-group-by-category

### GET /api/v1/items/statistics/min-single-brand-price
GET http://localhost:8080/api/v1/items/statistics/min-single-brand-price

### GET /api/v1/items/statistics/min-max-price
GET http://localhost:8080/api/v1/items/statistics/min-max-price?categoryName={{categoryName}}


### GET https://openapi.openbanking.or.kr/v2.0/account/transaction_list/fin_num
GET https://openapi.openbanking.or.kr/v2.0/account/transaction_list/fin_num
Authorization: Bearer {{accessToken}}