name: project-api

on:
  push:
    paths:
    - 'subprojects/server/project-api/src/**'
    - 'subprojects/repository/project-jpa-repository/src/main/**'
    - 'subprojects/common/src/main/**'
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  DOCKER_REGISTRY_URL: poten16.kr.ncr.ntruss.com
  DOCKER_IMAGE_NAME: project-api

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permisson for gradlew
      run: chmod +x gradlew

    - name: "Set env.DOCKER_IMAGE_TAG"
      shell: bash
      run: echo "DOCKER_IMAGE_TAG=dev-${GITHUB_SHA::6}" >> $GITHUB_ENV

    - name: Build Docker Image with Gradle
      run: ./gradlew :server:project-api:clean :server:project-api:bootBuildImage -PimageName=${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }} -PimageTag=${{ env.DOCKER_IMAGE_TAG }}

    - name: Log in to NCP Docker Registry
      run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login ${{ env.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

    - name: Push Docker Image to NCP Registry
      run: docker push ${{ env.DOCKER_REGISTRY_URL }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
